# Generated by Django 5.0.4 on 2024-12-02 17:44

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('brand', models.CharField(max_length=30)),
                ('size', models.IntegerField(validators=[django.core.validators.MaxValueValidator(4)])),
                ('refresh_rate', models.IntegerField(validators=[django.core.validators.MaxValueValidator(10)])),
                ('brightness', models.IntegerField(validators=[django.core.validators.MaxValueValidator(10)])),
                ('length', models.IntegerField(validators=[django.core.validators.MaxValueValidator(10)])),
                ('height', models.IntegerField(validators=[django.core.validators.MaxValueValidator(10)])),
                ('extra_characteristics', models.CharField(max_length=10000)),
                ('photo', models.ImageField(upload_to='images')),
                ('slug', models.SlugField(blank=True, editable=False, null=True, unique=True)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.monitouringuser')),
            ],
        ),
    ]
