# Generated by Django 5.0.4 on 2024-12-07 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitor',
            name='date_of_publication',
            field=models.DateField(auto_now=True),
        ),
    ]
